package model;

import org.junit.jupiter.api.Test;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import static org.junit.jupiter.api.Assertions.*;

class TransactionTest {
    
    @Test
    void testTransactionCreationWithAllParameters() {
        String id = "txn-123";
        LocalDateTime timestamp = LocalDateTime.of(2025, 12, 16, 10, 30);
        Transaction.Type type = Transaction.Type.DEPOSIT;
        BigDecimal amount = new BigDecimal("100.50");
        String description = "Test deposit";
        BigDecimal balanceAfter = new BigDecimal("500.00");
        
        Transaction transaction = new Transaction(id, timestamp, type, amount, description, balanceAfter);
        
        assertEquals(id, transaction.getId());
        assertEquals(timestamp, transaction.getTimestamp());
        assertEquals(type, transaction.getType());
        assertEquals(amount, transaction.getAmount());
        assertEquals(description, transaction.getDescription());
        assertEquals(balanceAfter, transaction.getBalanceAfter());
    }
    
    @Test
    void testTransactionTypesExist() {
        assertNotNull(Transaction.Type.DEPOSIT);
        assertNotNull(Transaction.Type.WITHDRAW);
        assertNotNull(Transaction.Type.TRANSFER);
        assertNotNull(Transaction.Type.INVEST);
        assertNotNull(Transaction.Type.GAIN_APPLIED);
    }
    
    @Test
    void testTransactionToString() {
        LocalDateTime timestamp = LocalDateTime.of(2025, 12, 16, 14, 30, 0);
        Transaction transaction = new Transaction(
            "id-1",
            timestamp,
            Transaction.Type.DEPOSIT,
            new BigDecimal("50.00"),
            "Salary deposit",
            new BigDecimal("550.00")
        );
        
        String result = transaction.toString();
        
        assertTrue(result.contains("2025-12-16 14:30:00"));
        assertTrue(result.contains("DEPOSIT"));
        assertTrue(result.contains("Salary deposit"));
        assertTrue(result.contains("50.00"));
        assertTrue(result.contains("550.00"));
    }
    
    @Test
    void testTransactionWithAutoGeneratedId() {
        Transaction transaction = new Transaction(
            LocalDateTime.now(),
            Transaction.Type.WITHDRAW,
            new BigDecimal("25.00"),
            "ATM withdrawal",
            new BigDecimal("475.00")
        );
        
        assertNotNull(transaction.getId());
        assertFalse(transaction.getId().isEmpty());
    }
}
